"""initial relational schema

Revision ID: 90b4640735d1
Revises: 
Create Date: 2026-08-28 01:00:05.448833
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '90b4640735d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisition_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32, collation='NOCASE'), nullable=False),
    sa.Column('name', sa.String(length=100, collation='NOCASE'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acquisition_method')),
    sa.UniqueConstraint('code', name='uq_acquisition_method_code'),
    sa.UniqueConstraint('name', name='uq_acquisition_method_name')
    )
    op.create_table('craft_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160, collation='NOCASE'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_craft_station')),
    sa.UniqueConstraint('name', name='uq_craft_station_name')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160, collation='NOCASE'), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment')),
    sa.UniqueConstraint('name', name='uq_equipment_name')
    )
    op.create_table('item_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160, collation='NOCASE'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_group')),
    sa.UniqueConstraint('name', name='uq_item_group_name')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160, collation='NOCASE'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill')),
    sa.UniqueConstraint('name', name='uq_skill_name')
    )
    op.create_table('item_subgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160, collation='NOCASE'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['item_group.id'], name=op.f('fk_item_subgroup_group_id_item_group'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_subgroup')),
    sa.UniqueConstraint('group_id', 'name', name='uq_item_subgroup_group_name')
    )
    with op.batch_alter_table('item_subgroup', schema=None) as batch_op:
        batch_op.create_index('ix_item_subgroup_group_id', ['group_id'], unique=False)

    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240, collation='NOCASE'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('subgroup_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('item_class', sa.String(length=160), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_consumable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['item_group.id'], name=op.f('fk_item_group_id_item_group'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subgroup_id'], ['item_subgroup.id'], name=op.f('fk_item_subgroup_id_item_subgroup'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item'))
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index('ix_item_group_id', ['group_id'], unique=False)
        batch_op.create_index('ix_item_item_class', ['item_class'], unique=False)
        batch_op.create_index('ix_item_name_nocase', ['name'], unique=False)
        batch_op.create_index('ix_item_rank', ['rank'], unique=False)
        batch_op.create_index('ix_item_subgroup_id', ['subgroup_id'], unique=False)

    op.create_table('item_acquisition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_item_acquisition_item_id_item'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['method_id'], ['acquisition_method.id'], name=op.f('fk_item_acquisition_method_id_acquisition_method'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_acquisition')),
    sa.UniqueConstraint('item_id', 'method_id', name='uq_item_acquisition_item_method')
    )
    with op.batch_alter_table('item_acquisition', schema=None) as batch_op:
        batch_op.create_index('ix_item_acquisition_item_id', ['item_id'], unique=False)
        batch_op.create_index('ix_item_acquisition_method_id', ['method_id'], unique=False)

    op.create_table('item_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('price_type', sa.String(length=32, collation='NOCASE'), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_item_price_price_nonnegative')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_item_price_item_id_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_price')),
    sa.UniqueConstraint('item_id', 'price_type', name='uq_item_price_item_type')
    )
    with op.batch_alter_table('item_price', schema=None) as batch_op:
        batch_op.create_index('ix_item_price_item_id', ['item_id'], unique=False)
        batch_op.create_index('ix_item_price_price_type', ['price_type'], unique=False)

    op.create_table('item_use_effect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('effect_type', sa.String(length=100, collation='NOCASE'), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_uses > 0', name=op.f('ck_item_use_effect_max_uses_positive')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_item_use_effect_item_id_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_use_effect'))
    )
    with op.batch_alter_table('item_use_effect', schema=None) as batch_op:
        batch_op.create_index('ix_item_use_effect_item_id', ['item_id'], unique=False)

    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_item_id', sa.Integer(), nullable=False),
    sa.Column('craft_station_id', sa.Integer(), nullable=False),
    sa.Column('output_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('energy_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('energy_cost >= 0', name=op.f('ck_recipe_energy_cost_nonnegative')),
    sa.CheckConstraint('output_quantity > 0', name=op.f('ck_recipe_output_quantity_positive')),
    sa.ForeignKeyConstraint(['craft_station_id'], ['craft_station.id'], name=op.f('fk_recipe_craft_station_id_craft_station'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['result_item_id'], ['item.id'], name=op.f('fk_recipe_result_item_id_item'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe'))
    )
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.create_index('ix_recipe_craft_station_id', ['craft_station_id'], unique=False)
        batch_op.create_index('ix_recipe_result_item_id', ['result_item_id'], unique=False)

    op.create_table('recipe_equipment_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_recipe_equipment_requirement_quantity_positive')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_recipe_equipment_requirement_equipment_id_equipment'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_equipment_requirement_recipe_id_recipe'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_equipment_requirement')),
    sa.UniqueConstraint('recipe_id', 'equipment_id', name='uq_recipe_equipment_requirement_recipe_equipment')
    )
    with op.batch_alter_table('recipe_equipment_requirement', schema=None) as batch_op:
        batch_op.create_index('ix_recipe_equipment_requirement_equipment_id', ['equipment_id'], unique=False)
        batch_op.create_index('ix_recipe_equipment_requirement_recipe_id', ['recipe_id'], unique=False)

    op.create_table('recipe_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_recipe_ingredient_quantity_positive')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_recipe_ingredient_item_id_item'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_ingredient_recipe_id_recipe'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredient')),
    sa.UniqueConstraint('recipe_id', 'item_id', name='uq_recipe_ingredient_recipe_item')
    )
    with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
        batch_op.create_index('ix_recipe_ingredient_item_id', ['item_id'], unique=False)
        batch_op.create_index('ix_recipe_ingredient_recipe_id', ['recipe_id'], unique=False)

    op.create_table('recipe_skill_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('required_level', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.CheckConstraint('required_level >= 0', name=op.f('ck_recipe_skill_requirement_required_level_nonnegative')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_skill_requirement_recipe_id_recipe'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_recipe_skill_requirement_skill_id_skill'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_skill_requirement')),
    sa.UniqueConstraint('recipe_id', 'skill_id', name='uq_recipe_skill_requirement_recipe_skill')
    )
    with op.batch_alter_table('recipe_skill_requirement', schema=None) as batch_op:
        batch_op.create_index('ix_recipe_skill_requirement_recipe_id', ['recipe_id'], unique=False)
        batch_op.create_index('ix_recipe_skill_requirement_skill_id', ['skill_id'], unique=False)

    op.create_table('recipe_skill_reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('experience_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.CheckConstraint('experience_amount >= 0', name=op.f('ck_recipe_skill_reward_experience_amount_nonnegative')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], name=op.f('fk_recipe_skill_reward_recipe_id_recipe'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name=op.f('fk_recipe_skill_reward_skill_id_skill'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_skill_reward')),
    sa.UniqueConstraint('recipe_id', 'skill_id', name='uq_recipe_skill_reward_recipe_skill')
    )
    with op.batch_alter_table('recipe_skill_reward', schema=None) as batch_op:
        batch_op.create_index('ix_recipe_skill_reward_recipe_id', ['recipe_id'], unique=False)
        batch_op.create_index('ix_recipe_skill_reward_skill_id', ['skill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_skill_reward', schema=None) as batch_op:
        batch_op.drop_index('ix_recipe_skill_reward_skill_id')
        batch_op.drop_index('ix_recipe_skill_reward_recipe_id')

    op.drop_table('recipe_skill_reward')
    with op.batch_alter_table('recipe_skill_requirement', schema=None) as batch_op:
        batch_op.drop_index('ix_recipe_skill_requirement_skill_id')
        batch_op.drop_index('ix_recipe_skill_requirement_recipe_id')

    op.drop_table('recipe_skill_requirement')
    with op.batch_alter_table('recipe_ingredient', schema=None) as batch_op:
        batch_op.drop_index('ix_recipe_ingredient_recipe_id')
        batch_op.drop_index('ix_recipe_ingredient_item_id')

    op.drop_table('recipe_ingredient')
    with op.batch_alter_table('recipe_equipment_requirement', schema=None) as batch_op:
        batch_op.drop_index('ix_recipe_equipment_requirement_recipe_id')
        batch_op.drop_index('ix_recipe_equipment_requirement_equipment_id')

    op.drop_table('recipe_equipment_requirement')
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_index('ix_recipe_result_item_id')
        batch_op.drop_index('ix_recipe_craft_station_id')

    op.drop_table('recipe')
    with op.batch_alter_table('item_use_effect', schema=None) as batch_op:
        batch_op.drop_index('ix_item_use_effect_item_id')

    op.drop_table('item_use_effect')
    with op.batch_alter_table('item_price', schema=None) as batch_op:
        batch_op.drop_index('ix_item_price_price_type')
        batch_op.drop_index('ix_item_price_item_id')

    op.drop_table('item_price')
    with op.batch_alter_table('item_acquisition', schema=None) as batch_op:
        batch_op.drop_index('ix_item_acquisition_method_id')
        batch_op.drop_index('ix_item_acquisition_item_id')

    op.drop_table('item_acquisition')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index('ix_item_subgroup_id')
        batch_op.drop_index('ix_item_rank')
        batch_op.drop_index('ix_item_name_nocase')
        batch_op.drop_index('ix_item_item_class')
        batch_op.drop_index('ix_item_group_id')

    op.drop_table('item')
    with op.batch_alter_table('item_subgroup', schema=None) as batch_op:
        batch_op.drop_index('ix_item_subgroup_group_id')

    op.drop_table('item_subgroup')
    op.drop_table('skill')
    op.drop_table('item_group')
    op.drop_table('equipment')
    op.drop_table('craft_station')
    op.drop_table('acquisition_method')
    # ### end Alembic commands ###

